export const universities =
    [
        "University of Dhaka",
        "University of Rajshahi",
        "Bangladesh Agricultural University",
        "Bangladesh University of Engineering & Technology",
        "University of Chittagong",
        "Jahangirnagar University",
        "Islamic University, Bangladesh",
        "Shahjalal University of Science & Technology",
        "Khulna University",
        "National University",
        "Bangladesh Open University",
        "Bangabandhu Sheikh Mujib Medical University",
        "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
        "Hajee Mohammad Danesh Science & Technology University",
        "Mawlana Bhashani Science & Technology University",
        "Patuakhali Science And Technology University",
        "Sher-e-Bangla Agricultural University",
        "Chittagong University of Engineering & Technology",
        "Rajshahi University of Engineering & Technology",
        "Khulna University of Engineering & Technology",
        "Dhaka University of Engineering & Technology",
        "Noakhali Science & Technology University",
        "Jagannath University",
        "Comilla University",
        "Jatiya Kabi Kazi Nazrul Islam University",
        "Chittagong Veterinary and Animal Sciences University",
        "Sylhet Agricultural University",
        "Jessore University of Science & Technology",
        "Pabna University of Science and Technology",
        "Begum Rokeya University, Rangpur",
        "Bangladesh University of Professionals",
        "Bangabandhu Sheikh Mujibur Rahman Science & Technology University",
        "Bangladesh University of Textiles",
        "University of Barishal",
        "Rangamati Science and Technology University",
        "Bangabandhu Sheikh Mujibur Rahman Maritime University, Bangladesh",
        "Islamic Arabic University",
        "Chittagong Medical University",
        "Rajshahi Medical University",
        "Rabindra University, Bangladesh",
        "Bangabandhu Sheikh Mujibur Rahman Digital University, Bangladesh",
        "Sheikh Hasina University",
        "Khulna Agricultural University",
        "Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University",
        "Bangamata Sheikh Fazilatunessa Mujib Medical University, Sylhet",
        "Bangabandhu Sheikh Mujibur Rahman Aviation And Aerospace University (BSMRAAU)",
        "Chandpur Science and Technology University",
        "Bangabandhu Sheikh Mujibur Rahman University, Kishoreganj",
        "Hobiganj Agricultural University",
        "Sheikh Hasina Medical University, Khulna",
        "Kurigram Agricultural University",
        "Sunamganj Science and Technology University",
        "Bangabandhu Sheikh Mujibur Rahman Science & Technology University, Pirojpur",
        "Bangabandhu Sheikh Mujibur Rahman University, Naogaon",
        "Mujibnagar University, Meherpur",
        "Medical University",
        "Others"
    ];

export const departments =
    [
        'Accounting and Information Systems',
        'Agronomy & Agricultural Extention',
        'Anthropology',
        'Applied Chemistry and Chemical Engineering',
        'Applied Mathematics',
        'Applied statistics',
        'Arabic',
        'Architecture',
        'Banking and Insurance',
        'Biochemistry & Molecular Biology',
        'Biochemistry and Motivation Science',
        'Biological Science',
        'Biomedical Engineering',
        'Botany',
        'Business Administration',
        'Chemical Engineering',
        'Chemistry',
        'Chinese Language and Culture',
        'Civil Engineering',
        'Communication Disorders',
        'Computer Science & Engineering',
        'Criminology',
        'Crop Science & Technology',
        'Development Studies',
        'Disaster science and management',
        'Economics',
        'Education & Research Institute',
        'Electrical & Electronic Engineering',
        'English',
        'ESOL',
        'Finance',
        'Fisheries',
        'Footwear engineering',
        'French Language and Culture',
        'Glass and Ceramic Engineering',
        'Grafix Design, Crafts & History of art',
        'Genetic Engineering & Biotechnology',
        'Geography and ecology',
        'Geology and Mining',
        'Health Economics',
        'History',
        'Humanities',
        'Information & Communication Engineering',
        'Information Science & Library Management',
        'Information technology and Library management',
        'Industrial and Production Engineering',
        'International Business',
        'International Relation',
        'Islamic History & Culture',
        'Islamic Studies',
        'Japanese Language and Culture',
        'Japanese Studies',
        'Law',
        'Law & Land Administration',
        'Leather Products Engineering',
        'Leather engineering',
        'Management',
        'Management Information Systems',
        'Management studies',
        'Marketing',
        'Mass Communication & Journalism',
        'Material Science & Engineering',
        'Mathematics',
        'Material Science & Engineering',
        'Math',
        'Medical Psychology',
        'Mechanical Engineering',
        'Metallurgical and Materials Engineering',
        'Microbiology',
        'Music',
        'Naval Architecture and Marine Engineering',
        'Nuclear engineering',
        'Nutrition and Food Science',
        'Oceanography',
        'Organization Strategy and Leadership',
        'Painting, Oriental Art & Printing',
        'Pali and Buddhist Studies',
        'Peace and Conflict Studies',
        'Persian language and literature',
        'Pharmacy',
        'Philosophy',
        'Physical Education and Sports Sciences',
        'Physics',
        'Political Science',
        'Population Science & Human Resource Development',
        'Population Sciences',
        'Pottery & Sculpture',
        'Print and Publication Studies',
        'Printing and Publication Studies',
        'Psychology',
        'Public administration',
        'Robotics and Mechanics Engineering',
        'Sanskrit',
        'Social Work',
        'Sociology',
        'Software engineering',
        'Soil, Water, and Environment Science',
        'Statistics',
        'Television, Film, and Photography',
        'Theatre',
        'Tourism and Hospitality Management',
        'Urdu',
        'Urban and Regional Planning',
        'Veterinary & Animal Sciences',
        'Water Resources Engineering',
        'Women and Gender Studies',
        'World Religion and Culture',
        'Zoology',
        'MBBS',
        'Others'
    ];

// export const departments =
//     [
//         'Accounting and Information Systems',
//         'Agronomy & Agricultural Extention',
//         'Anthropology',
//         'Applied Chemistry and Chemical Engineering',
//         'Applied Mathematics',
//         'Applied statistics',
//         'Arabic',
//         'Banking and Insurance',
//         'Biochemistry & Molecular Biology',
//         'Biochemistry and Motivation Science',
//         'Biological Science',
//         'Botany',
//         'Business Administration',
//         'Chemistry',
//         'Chinese Language and Culture',
//         'Communication Disorders',
//         'Computer Science & Engineering',
//         'Criminology',
//         'Crop Science & Technology',
//         'Development Studies',
//         'Disaster science and management',
//         'Economics',
//         'Education & Research Institute',
//         'Electrical & Electronic Engineering',
//         'English',
//         'ESOL',
//         'Finance',
//         'Fisheries',
//         'Footwear engineering',
//         'French Language and Culture',
//         'Grafix Design, Crafts & History of art',
//         'Genetic Engineering & Biotechnology',
//         'Geography and ecology',
//         'Geology and Mining',
//         'Health Economics',
//         'History',
//         'Information & Communication Engineering',
//         'Information Science & Library Management',
//         'Information technology and Library management',
//         'International Business',
//         'International Relation',
//         'Islamic History & Culture',
//         'Islamic Studies',
//         'Japanese Language and Culture',
//         'Japanese Studies',
//         'Linguistics',
//         'Law',
//         'Law & Land Administration',
//         'Leather Products Engineering',
//         'Leather engineering',
//         'Management',
//         'Management Information Systems',
//         'Management studies',
//         'Marketing',
//         'Mass Communication & Journalism',
//         'Material Science & Engineering',
//         'Mathematics',
//         'Material Science & Engineering',
//         'Math',
//         'Medical Psychology',
//         'Microbiology',
//         'Music',
//         'Nuclear engineering',
//         'Nutrition and Food Science',
//         'Oceanography',
//         'Organization Strategy and Leadership',
//         'Painting, Oriental Art & Printing',
//         'Pali and Buddhist Studies',
//         'Peace and Conflict Studies',
//         'Persian language and literature',
//         'Pharmacy',
//         'Philosophy',
//         'Physical Education and Sports Sciences',
//         'Physics',
//         'Political Science',
//         'Population Science & Human Resource Development',
//         'Population Sciences',
//         'Pottery & Sculpture',
//         'Print and Publication Studies',
//         'Printing and Publication Studies',
//         'Psychology',
//         'Public administration',
//         'Robotics and Mechanics Engineering',
//         'Sanskrit',
//         'Social Work',
//         'Sociology',
//         'Software engineering',
//         'Soil, Water, and Environment Science',
//         'Statistics',
//         'Television, Film, and Photography',
//         'Theatre',
//         'Tourism and Hospitality Management',
//         'Urdu',
//         'Veterinary & Animal Sciences',
//         'Women and Gender Studies',
//         'World Religion and Culture',
//         'Zoology'
//     ];


// export const departments =
//     [
//         // Engineering and Technology
//         'Computer Science and Engineering',
//         'Electrical and Electronic Engineering',
//         'Information and Communication Engineering',
//         'Information and Communication Technology',
//         'Information Technology',
//         'Software Engineering',
//         'Biomedical Engineering',
//         'Civil Engineering',
//         'Mechanical Engineering',
//         'Chemical Engineering',
//         'Industrial and Production Engineering',
//         'Textile Engineering',

//         // Medical and Health Sciences
//         'Medicine (MBBS)',
//         'Dental Surgery (BDS)',
//         'Pharmacy',
//         'Nursing',
//         'Public Health',
//         'Physiotherapy',

//         // Business and Management
//         'Business Administration (BBA)',
//         'Economics',
//         'Accounting',
//         'Finance',
//         'Marketing',
//         'Management',
//         'Human Resource Management',

//         // Science
//         'Physics',
//         'Chemistry',
//         'Mathematics',
//         'Biology',
//         'Environmental Science',
//         'Statistics',

//         // Social Sciences
//         'Sociology',
//         'Psychology',
//         'Political Science',
//         'Anthropology',
//         'International Relations',
//         'Development Studies',

//         // Arts and Humanities
//         'Bengali Language and Literature',
//         'English Language and Literature',
//         'History',
//         'Philosophy',
//         'Fine Arts',
//         'Linguistics',

//         // Law
//         'LLB (Bachelor of Laws)',
//         'LLM (Master of Laws)',
//         'Criminal Law',
//         'Corporate Law',
//         'International Law',

//         // Agriculture
//         'Agricultural Science',
//         'Agronomy',
//         'Horticulture',
//         'Soil Science',
//         'Agricultural Economics',
//         'Animal Husbandry',

//         // Education
//         'Education',
//         'Educational Psychology',
//         'Curriculum and Instruction',
//         'Educational Leadership',
//         'Special Education',
//         'Others'
//     ];



// export const departments =
//     [
//         'Philosophy',
//         'History',
//         'English',
//         'Bangla',
//         'Islamic History & Culture',
//         'Arabic',
//         'Islamic Studies',
//         'Music',
//         'Theatre',
//         'Persian language and literature',
//         'Urdu',
//         'Sanskrit',
//         'Law',
//         'Law & Land Administration',
//         'Economics',
//         'Political Science',
//         'Mass Communication & Journalism',
//         'Information Science & Library Management',
//         'Public administration',
//         'Social Work',
//         'Anthropology',
//         'Folklore',
//         'International Relation',
//         'Painting, Oriental Art & Printing',
//         'Pottery & Sculpture',
//         'Graphics Design, Crafts & History of art',
//         'Education & Research Institute',
//         'Accounting and Information Systems',
//         'Management studies',
//         'Marketing',
//         'Finance',
//         'Banking and Insurance',
//         'Tourism and Hospitality Management',
//         'Business Administration',
//         'Mathematics',
//         'Physics',
//         'Chemistry',
//         'Statistics',
//         'Biochemistry & Molecular Biology',
//         'Pharmacy',
//         'Population Science & Human Resource Development',
//         'Applied Mathematics',
//         'Physical Education and Sports Sciences',
//         'Psychology',
//         'Botany',
//         'Zoology',
//         'Genetic Engineering & Biotechnology',
//         'Medical Psychology',
//         'Microbiology',
//         'Agronomy & Agricultural Extension',
//         'Crop Science & Technology',
//         'Computer Science & Engineering',
//         'Electrical & Electronic Engineering',
//         'Information & Communication Engineering',
//         'Applied Chemistry and Chemical Engineering',
//         'Material Science & Engineering',
//         'Geography and ecology',
//         'Geology and Mining',
//         'Fisheries',
//         'Veterinary & Animal Sciences'
//     ];

export const sessions =
    [
        '2010-2011',
        '2011-2012',
        '2012-2013',
        '2013-2014',
        '2014-2015',
        '2015-2016',
        '2016-2017',
        '2017-2018',
        '2018-2019',
        '2019-2020',
        '2020-2021',
        '2021-2022',
        '2022-2023',
        '2023-2024',
        '2024-2025'
    ];


export const roles =
    [
        'Member',
        'President',
        'Vice President',
        'General Secretary',
        'Joint Secretary',
        'Treasurer',
        'Organizing Secretary',
        'Office Secretary',
        'Publication Secretary',
        'Cultural Secretary',
        'Sports Secretary',
        'Science and Technology Secretary',
        'Social Welfare Secretary',
        'Debate Secretary',
        'Recruitment Secretary',
        'Public Relations Secretary',
        'Alumni Secretary',
        'Advisor',
        'Patron'
    ];

export const navLinks = [
    { title: 'হোম', path: '/' },
    // { title: 'Profile', path: '/profile' },
    { title: 'সদস্যবৃন্দ', path: '/members' },
    { title: 'বর্তমান কমিটি', path: '/committee' },
    { title: 'গ্যালারি', path: '/gallery' },
    { title: 'আমাদের সম্পর্কে', path: '/about-us' },
    // { title: 'Notices', path: '/notices' },
    // { title: 'Login', path: '/login' },
    // { title: 'Signup', path: '/signup' },
];
// export const navLinks = [
//     { title: 'Home', path: '/' },
//     // { title: 'Profile', path: '/profile' },
//     { title: 'Members', path: '/members' },
//     { title: 'Gallery', path: '/gallery' },
//     // { title: 'Notices', path: '/notices' },
//     // { title: 'Login', path: '/login' },
//     // { title: 'Signup', path: '/signup' },
// ];

export const themes = [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
];
